### ISSUE TITLE
does not append \n before appending link since Obsidian version 0.9.22

### ISSUE THREAD

**Issue by seb-mm** [mrjackphil/obsidian-crosslink-between-notes#3] opened 2020-12-08 19:07 UTC
Until Obsidian version 0.9.20 the plugin worked great.
Since 0.9.22 the plugin does not append a new line (`\n`) before appending the link to the linked site.

How the page looks before using the plugin.
![grafik](https://user-images.githubusercontent.com/72164229/101528764-fcd73180-398f-11eb-9848-b0b504b7f8b6.png)

How it looks after using the plugin.
![grafik](https://user-images.githubusercontent.com/72164229/101528870-1e381d80-3990-11eb-9159-46efe3d6756c.png)

How it should look.
![grafik](https://user-images.githubusercontent.com/72164229/101528965-3445de00-3990-11eb-917e-6a5c306ad2f6.png)

Something in Obsidian 0.9.22 or perhaps 0.9.21 must have changed how it handles appending `\n` to it.
A fix would be greatly appreciated :)

**Comment by lishid** [comment] 2020-12-09 10:30
Caused by a bug in Obsidian v0.9.21 and 0.9.22. Will be fixed in the next release.

**Comment by seb-mm** [comment] 2020-12-09 10:31
Thank you @lishid :)

**Closed as completed** 2020-12-09 11:37 UTC
